version: "3"
services:
  cli:
    container_name: narou-cli
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - LANG=en_US.UTF-8
    volumes:
      - ./:/home/node/app
      - ~/.config/narou-cli:/home/node/.config/narou-cli
    command: "npm start"
